from __future__ import annotations

import re
from dataclasses import dataclass


_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True)
class Kline5MinSchemaConfig:
    db_path: str = "dfs://kline_5min"
    table_name: str = "kline_5min"
    start_month: int = 200501
    end_month: int = 203012
    hash_buckets: int = 10


def _validate_identifier(name: str) -> None:
    if not _IDENT_RE.match(name):
        raise ValueError(
            f"Invalid DolphinDB identifier: {name!r}. "
            "Only letters/digits/underscore are allowed, and it must not start with a digit."
        )


def build_kline_5min_init_script(
    *,
    db_path: str = "dfs://kline_5min",
    table_name: str = "kline_5min",
    start_month: int = 200501,
    end_month: int = 203012,
    hash_buckets: int = 10,
) -> str:
    """
    Build a DolphinDB script that creates (if missing) a composite-partitioned DFS table:
    - VALUE partition on explicit `month` int column (yyyymm)
    - HASH partition on `ts_code` with `hash_buckets`
    - sortColumns = [`ts_code`, `trade_time`]
    - keepDuplicates = LAST
    """
    _validate_identifier(table_name)
    if not db_path.startswith("dfs://"):
        raise ValueError(f"db_path must start with 'dfs://': {db_path!r}")
    if start_month > end_month:
        raise ValueError(f"start_month must be <= end_month: {start_month} > {end_month}")
    if hash_buckets <= 0:
        raise ValueError("hash_buckets must be positive")

    # Note: Use explicit backtick identifier for the table name to avoid quoting pitfalls.
    #       Keep `month` as a real column to maximize partition pruning.
    return f"""
// Auto-generated by AlphaHome
def alphahome_init_kline_5min(dbPath, tblName, startMonth, endMonth, hashBuckets) {{
    if(!existsDatabase(dbPath)) {{
        dbMonth = database("", VALUE, startMonth..endMonth)
        dbHash  = database("", HASH, [SYMBOL, hashBuckets])
        db = database(dbPath, COMPO, [dbMonth, dbHash])
    }} else {{
        db = database(dbPath)
    }}

    if(!existsTable(dbPath, tblName)) {{
        schema = table(
            1:0,
            `ts_code`trade_time`month`open`high`low`close`vol`amount,
            [SYMBOL, TIMESTAMP, INT, DOUBLE, DOUBLE, DOUBLE, DOUBLE, LONG, DOUBLE]
        )
        db.createPartitionedTable(
            schema,
            tblName,
            `month`ts_code
        )
    }}
    return 1
}}

alphahome_init_kline_5min("{db_path}", "{table_name}", {start_month}, {end_month}, {hash_buckets})
""".strip()


def build_drop_database_script(*, db_path: str) -> str:
    """Build a DolphinDB script to drop a DFS database if it exists."""
    if not db_path.startswith("dfs://"):
        raise ValueError(f"db_path must start with 'dfs://': {db_path!r}")
    return f"""
// Auto-generated by AlphaHome
if (existsDatabase("{db_path}")) {{
    dropDatabase("{db_path}")
}}
return 1
""".strip()

